# Generated by Django 6.0.6 on 2026-06-10 13:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text='Введите номер телефона',
                max_length=25,
                null=True,
                region=None,
                verbose_name='Номер телефона',
            ),
        ),
    ]
