# Generated by Django 6.0.6 on 2026-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[('cash', 'Оплата наличными'), ('transfer', 'Перевод на счет'), ('stripe_transfer', 'Stripe')],
                max_length=20,
                verbose_name='Способ оплаты',
            ),
        ),
    ]
