# Generated by Django 6.0.6 on 2026-06-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_date_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[('cash', 'Оплата наличными'), ('transfer', 'Перевод на счет'), ('stripe_transfer', 'Stripe')],
                default='stripe_transfer',
                max_length=20,
                verbose_name='Способ оплаты',
            ),
        ),
    ]
